import { TReviwe } from "@/interfaces/types/pageTypes/products.type";

export const allReviwes = [
  {
    id: 1,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 2,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 3,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 4,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 5,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 6,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 7,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 8,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 9,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
  {
    id: 10,
    name: "string",
    position: "string",
    avatar: "product-icon",
    rating: 5,
    text: "string",
    caseUrl: "string",
  },
] satisfies TReviwe[];
