import { Header } from "@/components/layout/header/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body suppressHydrationWarning={true}>
        <div className="page">
          <Header />
          <main>{children}</main>
          <footer>footer</footer>
        </div>
      </body>
    </html>
  );
}
